name: Android

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        arch: [armeabi-v7a, arm64-v8a]
        ndk: ["r22b", "r27c"]
        ndk_sdkver: ["21", "30"]

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Android-${{ matrix.arch }}-${{ matrix.ndk }}-${{ matrix.ndk_sdkver }}
      cancel-in-progress: true
    steps:
#      - name: Maximize build space
#        uses: easimon/maximize-build-space@master
#        with:
#          build-mount-path: /home/runner/.xmake
#          root-reserve-mb: 10240
#          temp-reserve-mb: 10240
#          remove-dotnet: true
#          remove-android: true
#          remove-haskell: true
#          remove-codeql: true
#          remove-docker-images: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: ".xmake-cache"
          actions-cache-key: "android"

      - name: Prepare
        run: |
          if test ${{ matrix.ndk }} = "r22b"; then
            wget -q -O ndk.zip https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk }}-linux-x86_64.zip
          else
            wget -q -O ndk.zip https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk }}-linux.zip
          fi
          unzip -q -o ./ndk.zip

      - name: Tests
        run: |
          xmake l ./scripts/test.lua -vD -p android --ndk=`pwd`/ndk --ndk_sdkver=${{ matrix.ndk_sdkver }} -a ${{ matrix.arch }}
